apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 30008
  type: NodePort